import type { AppData, Model, Round, Scorecard, Scores } from './types'
import { computeTotal } from './scoring'

function mk(scores: Partial<Scores>): Scores {
  return {
    bootyShape: 0,
    bootyMovement: 0,
    dancePerformance: 0,
    bodyHarmony: 0,
    sexAppeal: 0,
    sensuality: 0,
    faceBeauty: 0,
    presentation: 0,
    skinQuality: 0,
    authenticity: 0,
    nudity: 0,
    perfectBodyBonus: 0,
    ...scores,
  }
}

const now = new Date().toISOString()

const B = '/Bootyology/photos'

const models: Model[] = [
  // ── Hall of Fame ──────────────────────────────────────────────────────────
  {
    id: 'm_moneca',
    name: 'Moneca Doll Paradise',
    emoji: '👑',
    accent: '#e3bc63',
    tags: ['Favourite', 'Number One'],
    discoveredYear: 2018,
    notes: 'The number one. The benchmark every round is measured against.',
    favorite: true,
    archived: false,
    photoUrl: `${B}/moneca/1.jpg`,
    photos: [`${B}/moneca/2.jpg`, `${B}/moneca/3.jpg`, `${B}/moneca/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_tiffany',
    name: 'Tiffany Days',
    emoji: '💎',
    accent: '#8ab6d9',
    tags: ['Favourite', 'BBW'],
    discoveredYear: 2019,
    notes: 'One of the curvy icons that got me into the BBW space.',
    favorite: true,
    archived: false,
    photoUrl: `${B}/tiffany/1.jpg`,
    photos: [`${B}/tiffany/2.jpg`, `${B}/tiffany/3.jpg`, `${B}/tiffany/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_jazzmine',
    name: 'Jazzmine Jonez',
    emoji: '🎷',
    accent: '#c98ad9',
    tags: ['Favourite', 'BBW'],
    discoveredYear: 2019,
    notes: 'A curvy icon — part of what opened up the BBW appreciation.',
    favorite: true,
    archived: false,
    photoUrl: `${B}/jazzmine/1.jpg`,
    photos: [`${B}/jazzmine/2.jpg`, `${B}/jazzmine/3.jpg`, `${B}/jazzmine/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_paula',
    name: 'Paula Curvez',
    emoji: '🌹',
    accent: '#d98aae',
    tags: ['Favourite'],
    discoveredYear: 2019,
    notes: 'Unforgettable — always in the conversation.',
    favorite: true,
    archived: false,
    photoUrl: `${B}/paula/1.jpg`,
    photos: [`${B}/paula/2.jpg`, `${B}/paula/3.jpg`, `${B}/paula/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_rosee',
    name: 'Rosee Divine',
    emoji: '🌺',
    accent: '#8ad9b0',
    tags: ['Favourite', 'Original'],
    discoveredYear: 2017,
    notes: 'One of the first two discovered — kicked off this whole interest.',
    favorite: true,
    archived: false,
    photoUrl: `${B}/rosee/1.jpg`,
    photos: [`${B}/rosee/2.jpg`, `${B}/rosee/3.jpg`, `${B}/rosee/4.jpg`],
    createdAt: now,
  },
  // ── CM Originals (January 2021 Collection) ────────────────────────────────
  {
    id: 'm_aqua',
    name: 'Aqua Witha Choppa',
    emoji: '💧',
    accent: '#5bc8d4',
    tags: ['Original'],
    discoveredYear: 2021,
    notes: 'Standout from the January 2021 collection.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/aqua/1.jpg`,
    photos: [`${B}/aqua/2.jpg`, `${B}/aqua/3.jpg`, `${B}/aqua/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_asialovey',
    name: 'Asia Lovey',
    emoji: '🌸',
    accent: '#f0a0b0',
    tags: ['Original'],
    discoveredYear: 2021,
    notes: 'Strong presence in the January 2021 set.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/asialovey/1.jpg`,
    photos: [`${B}/asialovey/2.jpg`, `${B}/asialovey/3.jpg`, `${B}/asialovey/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_asiaperez',
    name: 'Asia Perez',
    emoji: '🌴',
    accent: '#ff8060',
    tags: ['Original'],
    discoveredYear: 2021,
    notes: 'Coral energy — bold from the first frame.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/asiaperez/1.jpg`,
    photos: [`${B}/asiaperez/2.jpg`, `${B}/asiaperez/3.jpg`, `${B}/asiaperez/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_blackeuro',
    name: 'Black Euro',
    emoji: '🖤',
    accent: '#8898a8',
    tags: ['Original'],
    discoveredYear: 2021,
    notes: 'Sleek Euro style, effortlessly confident.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/blackeuro/1.jpg`,
    photos: [`${B}/blackeuro/2.jpg`, `${B}/blackeuro/3.jpg`, `${B}/blackeuro/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_juicy',
    name: 'Dat Bitch Named Juicy',
    emoji: '🍑',
    accent: '#ffb060',
    tags: ['BBW'],
    discoveredYear: 2021,
    notes: 'Lives up to the name — unfiltered, full-throttle presence.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/juicy/1.jpg`,
    photos: [`${B}/juicy/2.jpg`, `${B}/juicy/3.jpg`, `${B}/juicy/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_elegance',
    name: 'Elegance Ellie Yabish',
    emoji: '✨',
    accent: '#b898c8',
    tags: ['Original'],
    discoveredYear: 2021,
    notes: 'The name says it all — refined and smooth in every shot.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/elegance/1.jpg`,
    photos: [`${B}/elegance/2.jpg`, `${B}/elegance/3.jpg`, `${B}/elegance/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_herrr',
    name: 'Herrr',
    emoji: '👸',
    accent: '#c8a8e8',
    tags: ['Original', 'BBW'],
    discoveredYear: 2021,
    notes: 'Major curves, major attitude. One of the bigger collections.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/herrr/1.jpg`,
    photos: [`${B}/herrr/2.jpg`, `${B}/herrr/3.jpg`, `${B}/herrr/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_jadagemz',
    name: 'Jada Gemz',
    emoji: '💍',
    accent: '#d8a040',
    tags: ['Original'],
    discoveredYear: 2021,
    notes: 'A gem — compact collection but every shot counts.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/jadagemz/1.jpg`,
    photos: [`${B}/jadagemz/2.jpg`, `${B}/jadagemz/3.jpg`, `${B}/jadagemz/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_jaymoney',
    name: 'Jay Money',
    emoji: '💰',
    accent: '#78b080',
    tags: ['Original'],
    discoveredYear: 2021,
    notes: 'Rich in presence — strong portfolio from the 2021 session.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/jaymoney/1.jpg`,
    photos: [`${B}/jaymoney/2.jpg`, `${B}/jaymoney/3.jpg`, `${B}/jaymoney/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_kittylov',
    name: 'Kitty Lov',
    emoji: '🐱',
    accent: '#f07050',
    tags: ['Original'],
    discoveredYear: 2021,
    notes: 'Warm, playful energy — one of the more charismatic shoots.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/kittylov/1.jpg`,
    photos: [`${B}/kittylov/2.jpg`, `${B}/kittylov/3.jpg`, `${B}/kittylov/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_scarlett',
    name: 'Scarlett',
    emoji: '❤️‍🔥',
    accent: '#cc2244',
    tags: ['Original'],
    discoveredYear: 2021,
    notes: 'Red-hot energy — Scarlett delivers every time.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/scarlett/1.jpg`,
    photos: [`${B}/scarlett/2.jpg`, `${B}/scarlett/3.jpg`, `${B}/scarlett/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_spicyj',
    name: 'Spicy J',
    emoji: '🌶️',
    accent: '#e84030',
    tags: ['BBW'],
    discoveredYear: 2021,
    notes: 'Hot from the first frame — spice justified by the catalog.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/spicyj/1.jpg`,
    photos: [`${B}/spicyj/2.jpg`, `${B}/spicyj/3.jpg`, `${B}/spicyj/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_strellakat',
    name: 'Strella Kat',
    emoji: '⭐',
    accent: '#40c4b0',
    tags: ['Original'],
    discoveredYear: 2021,
    notes: 'Stellar look, teal personality — stands out in any lineup.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/strellakat/1.jpg`,
    photos: [`${B}/strellakat/2.jpg`, `${B}/strellakat/3.jpg`, `${B}/strellakat/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_suglips',
    name: 'Sug Lips',
    emoji: '💋',
    accent: '#e87888',
    tags: ['Original', 'BBW'],
    discoveredYear: 2021,
    notes: 'One of the largest collections — 208 shots speaks for itself.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/suglips/1.jpg`,
    photos: [`${B}/suglips/2.jpg`, `${B}/suglips/3.jpg`, `${B}/suglips/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_sugarjones',
    name: 'Sugar Jones',
    emoji: '🍯',
    accent: '#d4a848',
    tags: ['Original'],
    discoveredYear: 2021,
    notes: 'Sweet and smooth — the honey-gold aesthetic matches the vibe.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/sugarjones/1.jpg`,
    photos: [`${B}/sugarjones/2.jpg`, `${B}/sugarjones/3.jpg`, `${B}/sugarjones/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_sabella',
    name: 'The Real Sabella',
    emoji: '👄',
    accent: '#902858',
    tags: ['Original'],
    discoveredYear: 2021,
    notes: 'Commanding energy — "The Real" moniker well earned.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/sabella/1.jpg`,
    photos: [`${B}/sabella/2.jpg`, `${B}/sabella/3.jpg`, `${B}/sabella/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_rabi',
    name: 'YRB Rabi',
    emoji: '🐰',
    accent: '#9878d0',
    tags: ['Original'],
    discoveredYear: 2021,
    notes: 'Violet energy — stands out from the January 2021 pack.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/rabi/1.jpg`,
    photos: [`${B}/rabi/2.jpg`, `${B}/rabi/3.jpg`, `${B}/rabi/4.jpg`],
    createdAt: now,
  },
  {
    id: 'm_zarago',
    name: 'Zara Go',
    emoji: '🌟',
    accent: '#7850c0',
    tags: ['Original'],
    discoveredYear: 2021,
    notes: 'Bold violet presence — one of the strongest from ZaraGo collection.',
    favorite: false,
    archived: false,
    photoUrl: `${B}/zarago/1.jpg`,
    photos: [`${B}/zarago/2.jpg`, `${B}/zarago/3.jpg`, `${B}/zarago/4.jpg`],
    createdAt: now,
  },
]

const rounds: Round[] = [
  {
    id: 'r_debut',
    name: 'Debut Round',
    date: '2025-09-14',
    notes: 'The opening round — establishing a baseline for the favourites.',
    createdAt: now,
  },
  {
    id: 'r_gold',
    name: 'Golden Hour',
    date: '2026-02-01',
    notes: 'Warm-toned styling theme, second pass on the roster.',
    createdAt: now,
  },
]

interface SeedCard {
  modelId: string
  roundId: string
  date: string
  scores: Scores
  comments?: string
}

const rawCards: SeedCard[] = [
  // ── Debut round ───────────────────────────────────────────────────────────
  {
    modelId: 'm_moneca',
    roundId: 'r_debut',
    date: '2025-09-14',
    scores: mk({
      bootyShape: 25, bootyMovement: 24, dancePerformance: 20,
      bodyHarmony: 14, sexAppeal: 14, sensuality: 14,
      faceBeauty: 10, presentation: 9,
      skinQuality: 9, authenticity: 10,
      nudity: 0, perfectBodyBonus: 10,
    }),
    comments: 'Impeccable from every angle, hypnotic control, stayed tasteful. The standard. 159/165.',
  },
  {
    modelId: 'm_tiffany',
    roundId: 'r_debut',
    date: '2025-09-14',
    scores: mk({
      bootyShape: 22, bootyMovement: 21, dancePerformance: 17,
      bodyHarmony: 13, sexAppeal: 13, sensuality: 13,
      faceBeauty: 9, presentation: 8,
      skinQuality: 8, authenticity: 8,
      nudity: 0, perfectBodyBonus: 8,
    }),
    comments: 'Exceptional roundness, smooth tempo control, great presence.',
  },
  {
    modelId: 'm_jazzmine',
    roundId: 'r_debut',
    date: '2025-09-14',
    scores: mk({
      bootyShape: 21, bootyMovement: 21, dancePerformance: 16,
      bodyHarmony: 12, sexAppeal: 13, sensuality: 13,
      faceBeauty: 8, presentation: 8,
      skinQuality: 8, authenticity: 9,
      nudity: 0, perfectBodyBonus: 6,
    }),
    comments: 'Strong bounce and rhythm, confident energy throughout.',
  },
  {
    modelId: 'm_paula',
    roundId: 'r_debut',
    date: '2025-09-14',
    scores: mk({
      bootyShape: 20, bootyMovement: 19, dancePerformance: 14,
      bodyHarmony: 12, sexAppeal: 12, sensuality: 12,
      faceBeauty: 8, presentation: 8,
      skinQuality: 9, authenticity: 10,
      nudity: 0, perfectBodyBonus: 6,
    }),
    comments: 'Great waist-to-hip ratio, flatters every outfit.',
  },
  {
    modelId: 'm_rosee',
    roundId: 'r_debut',
    date: '2025-09-14',
    scores: mk({
      bootyShape: 21, bootyMovement: 19, dancePerformance: 16,
      bodyHarmony: 12, sexAppeal: 13, sensuality: 12,
      faceBeauty: 9, presentation: 8,
      skinQuality: 9, authenticity: 9,
      nudity: 0, perfectBodyBonus: 6,
    }),
    comments: 'Divine indeed — strong all-rounder, eyes connect well.',
  },
  // ── Golden Hour round ─────────────────────────────────────────────────────
  {
    modelId: 'm_moneca',
    roundId: 'r_gold',
    date: '2026-02-01',
    scores: mk({
      bootyShape: 25, bootyMovement: 25, dancePerformance: 20,
      bodyHarmony: 15, sexAppeal: 15, sensuality: 15,
      faceBeauty: 10, presentation: 10,
      skinQuality: 10, authenticity: 10,
      nudity: 0, perfectBodyBonus: 10,
    }),
    comments: 'Perfect. The ideal performance — 165/165. Every criterion maxed. The definitive standard.',
  },
  {
    modelId: 'm_tiffany',
    roundId: 'r_gold',
    date: '2026-02-01',
    scores: mk({
      bootyShape: 23, bootyMovement: 22, dancePerformance: 18,
      bodyHarmony: 14, sexAppeal: 13, sensuality: 14,
      faceBeauty: 9, presentation: 9,
      skinQuality: 8, authenticity: 7,
      nudity: 0, perfectBodyBonus: 8,
    }),
    comments: 'Stepped up the dance and styling noticeably.',
  },
  {
    modelId: 'm_rosee',
    roundId: 'r_gold',
    date: '2026-02-01',
    scores: mk({
      bootyShape: 22, bootyMovement: 20, dancePerformance: 17,
      bodyHarmony: 13, sexAppeal: 14, sensuality: 14,
      faceBeauty: 9, presentation: 9,
      skinQuality: 10, authenticity: 9,
      nudity: 0, perfectBodyBonus: 8,
    }),
    comments: 'Real improvement in flow and confidence.',
  },
  {
    modelId: 'm_jazzmine',
    roundId: 'r_gold',
    date: '2026-02-01',
    scores: mk({
      bootyShape: 22, bootyMovement: 20, dancePerformance: 17,
      bodyHarmony: 12, sexAppeal: 13, sensuality: 13,
      faceBeauty: 9, presentation: 8,
      skinQuality: 9, authenticity: 9,
      nudity: 0, perfectBodyBonus: 7,
    }),
    comments: 'Consistent and a touch sharper than the debut.',
  },
]

const scorecards: Scorecard[] = rawCards.map((c, i) => ({
  id: `sc_seed_${i}`,
  modelId: c.modelId,
  roundId: c.roundId,
  date: c.date,
  scores: c.scores,
  total: computeTotal(c.scores),
  comments: c.comments,
  createdAt: now,
}))

const defaultJudgeProfile = {
  xp: 0,
  level: 1,
  currentStreak: 0,
  longestStreak: 0,
  lastActiveDate: '',
  totalSessions: 0,
  gooning: 0,
  unexpectedOrgasms: 0,
}

export function seedData(): AppData {
  return {
    version: 1,
    models,
    rounds,
    scorecards,
    clips: [],
    settings: { theme: 'dark', rankBy: 'average', judgeName: 'Loyalty' },
    judgeProfile: defaultJudgeProfile,
    dailyChallenges: [],
    calendarEvents: [],
  }
}
